[tool.poetry]
name = "snowpy3"
version = "2018.11.2"
description = "Python 3 Library to interact with and manage a ServiceNow instance via JSONv2"
classifiers=[
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
authors = ["RCB <rcb@tangonine.com>"]
readme = 'README.md'
repository = "https://bitbucket.org/rcbalfour/snowpy3/src/"

[tool.poetry.dependencies]
python = "^3.2"
requests = "^2.20"
redis = "^2.10"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
